language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv sync
  - pipenv sync --dev
script:
  - pylint egress tests
  - flake8 egress tests
  - pytest --cov=egress --cov-report=xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
