apiVersion: v1
kind: Template
metadata:
  name: egress-setup-template
  annotations:
    description: "Data egress credentials"
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: postgresql
  type: Opaque
  data:
    database-user: dXJsCg==
    database-password: YnVja2V0Cg==
    database-name: dXJsCg==
- kind: Secret
  apiVersion: v1
  metadata:
    name: aws
  type: Opaque
  data:
    access-key-id: eHh4Cg==
    secret-access-key: eHh4Cg==
